name: base
channels:
  - conda-forge
dependencies:
  ####  Do not change Python version in this yaml! ###
  ####  If you need Python of different version,   ###
  ####  specify other base image in Dockerfile.     ###
  ####  GOOD PRACTICE: since conda is slow, specify as few conda packages as posssible    ###
  ####  For instance you may specify only non-python packages like ffmpeg, or cudatoolkit ###
  ####  Of course you may use only conda, but expect llong time image building            ###
  ####  - <channel>::package=0.0 ####
  # - pytorch::pytorch
  # - pytorch::torchvision
  # - cudatoolkit=11.3
  # - pytorch-lightning
  # - torchinfo
  - ffmpeg=4.3.1
